analyser:
  asns: all
  dist_threshold: 3
  figure_address: ./results/figures/
  min_anomalies: 0
  mode: M
  noise_sd_default: 0.02
  save_address: ./results/
  tolerance: 5
writer:
  asns: '600,12880,3833,13335,35160,57958'
  end: '2019-09-30'
  mode: L
  range: A2:E25
  save_address: ./data/
  time_window: 14
