analyser:
  asns: all
  dist_threshold: 3
  figure_address: ./results/figures/
  min_anomalies: 0
  mode: M
  noise_sd_default: 0.02
  save_address: ./results/
  tolerance: 5
writer:
  asns: 13335,12880,35160
  end: '2019-08-31'
  mode: D
  range: A2:E5
  save_address: ./data/
  time_window: 14
