import yaml
import argparse

parser = argparse.ArgumentParser()

parser.add_argument("-wm", help="mode for writer list/dates")
parser.add_argument("-wr", help="range for list", default="A2:E5")
parser.add_argument("-wsa", help="save address for writer", default="./data/")
parser.add_argument("-wt", help="time window for writer", default=14)
parser.add_argument("-wa", help="as numbers for writer")
parser.add_argument("-we", help="end time for writer")

parser.add_argument("-am", help="mode for analyser Madmax/LGhash")
parser.add_argument("-asa", help="save address for analyser", default="./results/")
parser.add_argument("-afa", help="save address for figures generated by analyser", default="./results/figures/")
parser.add_argument("-aa", help="as numbers for analyser", default="all")
parser.add_argument("-ama", help="minimum anomalies threshold for analyser", default=0)
parser.add_argument("-ans", help="standard deviation of white noise for Madmax", default=0.02)
parser.add_argument("-at", help="tolerance of safe zone for Madmax", default=5)
parser.add_argument("-ad", help="threshold for the distances of fingerprints", default=3)

args = parser.parse_args()

writer = {}
writer["mode"] = args.wm
writer["range"] = args.wr
writer["save_address"] = args.wsa
writer["time_window"] = args.wt
writer["asns"] = args.wa
writer["end"] = args.we
analyser = {}
analyser["mode"] = args.am
analyser["save_address"] = args.asa
analyser["figure_address"] = args.afa
analyser["asns"] = args.aa
analyser["min_anomalies"] = args.ama
analyser["noise_sd_default"] = args.ans
analyser["tolerance"] = args.at
analyser["dist_threshold"] = args.ad
configs = {}
configs["writer"] = writer
configs["analyser"] = analyser

with open("config.yml", 'w') as ymlfile:
    yaml.dump(configs, ymlfile)